DEFAULT_START_D = '2019-11-01'
DEFAULT_END_D = '2019-12-31'
START_DATE_CELL = "Q2"
END_DATE_CELL = "Q3"
BLUE_HEADER = (96, 211, 249)
ORANGE_HEADER = (255, 165, 0)
LINK_COL = "R"
GRAPH_DATES_COL = ["T","U"]
# sheets names
LIVE_STOCK = "Live Stock"
GRAPH_STOCK = "Graph Stock"
GRAPH_TOTAL = "Graph total money"
GRAPH_RETURN_PER_DAY = "Graph retrun per day "
CUMULATIVE_DALY_RETURN = "Cumulative Daly Return "
INDEX_TO_START_STOCK_VAL = 3
HYPER_LINK = "=HYPERLINK(\"#'{0}'!A1\", \"{0}\")"
HYPER_LINK_BACK = "=HYPERLINK(\"#'{0}'!A1\", \"{1}\")"
BACK_PLACE = "A1"
